sudo: false
language: go

go:
  - 1.13.x
  - master
os:
  - linux
  - osx
install: true

before_script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2

script:
  - go build
  - go test ./...
  - golangci-lint run